# Generated by Django 4.2.2 on 2023-06-19 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Car number')),
            ],
        ),
        migrations.CreateModel(
            name='Trains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='TrainNumber')),
                ('status', models.CharField(choices=[('NORM', 'normal'), ('CANCELLED', 'cancelled'), ('DIV', 'diverted')], default='normal', max_length=9, verbose_name='StatusOfTrain')),
                ('from_city', models.CharField(max_length=255, verbose_name='from')),
                ('to_city', models.CharField(max_length=255, verbose_name='to')),
                ('departure_date', models.DateTimeField(verbose_name='departure_date')),
                ('arrival_date', models.DateTimeField(verbose_name='arrival_date')),
            ],
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Seat number')),
                ('status', models.CharField(choices=[('FREE', 'free'), ('BOUGHT', 'bought')], default='FREE', max_length=6, verbose_name='SeatStatus')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='railway.cars')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cars',
            name='train',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='railway.trains'),
        ),
    ]
