# Generated by Django 4.2.2 on 2023-06-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seats',
            name='status',
            field=models.CharField(choices=[('FREE', 'free'), ('BOUGHT', 'bought')], default='free', max_length=6, verbose_name='SeatStatus'),
        ),
    ]
