# Generated by Django 4.2.2 on 2023-06-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0002_alter_seats_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seats',
            name='status',
            field=models.CharField(choices=[('FREE', 'free'), ('BOUGHT', 'bought')], max_length=6, verbose_name='SeatStatus'),
        ),
    ]
